<div style="max-width: 880px; margin: 20px auto 22px; padding: 0px; border-radius: 18px; border: 1px solid #e5e7eb; background: linear-gradient(180deg, #ffffff 0%, #f9fafb 100%); box-shadow: 0 8px 26px rgba(0,0,0,0.06); overflow: hidden;">

  <!-- Banner Header -->
  <div style="padding: 34px 32px 14px; text-align: center; line-height: 1.38;">
    <div style="font-size: 13px; letter-spacing: 0.14em; text-transform: uppercase; color: #6b7280; font-weight: bold; margin-bottom: 5px;">
      Session #1
    </div>
    <div style="font-size: 29px; font-weight: 800; color: #14276c; margin-bottom: 4px;">
      Introduction to Python | Part I
    </div>
    <div style="font-size: 16.5px; color: #374151; font-style: italic; margin-bottom: 0;">
      Data Science for Economics
    </div>
  </div>

  <!-- Logo Section -->
  <div style="background: none; text-align: center; margin: 30px 0 10px;">
    <img src="https://www.cemfi.es/images/Logo-Azul.png" alt="CEMFI Logo" style="width: 158px; filter: drop-shadow(0 2px 12px rgba(56,84,156,0.05)); margin-bottom: 0;">
  </div>

  <!-- Name -->
  <div style="font-family: 'Times New Roman', Times, serif; color: #38549c; text-align: center; font-size: 1.22em; font-weight: bold; margin-bottom: 0px;">
    Jesus Villota Miranda © 2025
  </div>

  <!-- Contact info -->
  <div style="font-family: 'Times New Roman', Times, serif; color: #38549c; text-align: center; font-size: 1em; margin-top: 7px; margin-bottom: 20px;">
    <a href="mailto:jesus.villota@cemfi.edu.es" style="color: #38549c; text-decoration: none; margin-right:8px;" title="Email">
      <!-- Email logo -->
      <!-- <img src="https://cdn-icons-png.flaticon.com/512/11679/11679732.png" alt="Email" style="width:18px; vertical-align:middle; margin-right:5px;"> -->
      jesus.villota@cemfi.edu.es
    </a>
    <span style="color:#9fa7bd;">|</span>
    <a href="https://www.linkedin.com/in/jesusvillotamiranda/" target="_blank" style="color: #38549c; text-decoration: none; margin-left:7px;" title="LinkedIn">
      <!-- LinkedIn logo -->
      <!-- <img src="https://1.bp.blogspot.com/-onvhHUdW1Us/YI52e9j4eKI/AAAAAAAAE4c/6s9wzOpIDYcAo4YmTX1Qg51OlwMFmilFACLcBGAsYHQ/s1600/Logo%2BLinkedin.png" alt="LinkedIn" style="width:17px; vertical-align:middle; margin-right:5px;"> -->
      LinkedIn
    </a>
  </div>
</div>


:::
Sources:
- Previous materials for this course (from Alba Miñano-Manero)
- Online course: [Python Programming for Data Science](https://www.tomasbeuzen.com/python-programming-for-data-science/README.html)
- Own contributions and adaptations.
:::

Welcome everyone to this short brush-up course in Python programming. Our aim over these two classes is to provide you with a solid foundation, ensuring you're well-prepared to make the most of the upcoming Data Science course taught by Joël.

<!-- [Joël Marbet](https://www.joelmarbet.com). -->

For some of you, this may mark your initial foray into programming. These first two classes are designed to acquaint you with the fundamental concepts you'll need moving forward. If certain concepts seem unfamiliar or daunting, don't panic. Programming presents a steep learning curve, you'll be amazed at how much you can achieve in a short time.

The topics we aim to cover in these lessons are:
1. Overview of the installation guidelines you've been provided (S1)
2. Jupyter Notebook foundations (S1)
3. Basic programming syntax. (S1)
4.  `NumPy` (S1)
5. Data management with `pandas`(S2)
6. Data visualization with `matplotlib` and `seaborn` (S2)

# **1. Overview of setup and installation**

<hr>

<img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Flogos-world.net%2Fwp-content%2Fuploads%2F2021%2F10%2FPython-Logo.png&f=1&nofb=1&ipt=71c37d83c19de1b87b943eaada21ff310edfb4b9591adcb42be86407c9045b50" width="200px" />

**What is Python?** 

Python is a high-level, general-purpose programming language designed by Guido van Rossum in the late 1980s. It acts as a translator, abstracting away the  details of computers and enabling us to communicate with them using a language that's easier for humans to understand. 

Python emphasizes readability, making it *straightforward* to write and understand code. It supports various programming paradigms, including procedural, where we provide a sequence of instructions; object-oriented, where we create objects with data and perform actions on them; and functional programming, where code is organized around functions. 

With a vast ecosystem of libraries and frameworks, Python is widely used across diverse applications, from web development and data analysis to artificial intelligence and scientific computing. Over the years, Python has transitioned from a specialized scientific computing language to a key player in data science, machine learning, and software development, thanks to its extensive open-source libraries and its adaptability to construct sophisticated data applications.

**Why Python?**
- Python is widely used, increasing the availability of resources that we, as end-users, can leverage.
- Python is free and open-source.
- Python is connected to many software platforms. This kind of integration with other software allows us to expand the functionality of software packages and customize solutions for specific data analysis needs.

However, setting up a Python environment for data science is not straightforward. We need an environment that contains all the packages/libraries in a compatible way. Achieving this isn't always easy.

**Installation** 

We can just install Python from the [official website](https://www.python.org/downloads/). This installation would have us equipped to write and run code directly from our terminal. However, this approach is rather unintuitive, especially for beginners who are just getting started with programming. That's where text editors come into play. Text editors provide a more user-friendly interface for writing and organizing code, offering features like syntax highlighting, auto-completion, and project management tools, making the coding process more intuitive and efficient for programmers of any level. 

We'll use [VSCode](https://code.visualstudio.com) as editor (aka **I**ntegrated **D**evelopment **E**nvironment). VSCode is a very popular editor because it supports almost any language and, by downloading the right extensions, we can addapt the coding to all levels of programming. In this course we will use all the Python extensions and the Jupyter Notebook ones (*python, pylance, jupyter, jupyter cell tags, jupyter keymap, jupyter notebook renderers, jupyter slide show, python indent, python debugger, Python extended*)

With the native Python installation we get a subset of basic packages, but to this environment we need to include the packages/libraries that we need for our particular tasks. Packages are extensions to the basic Python environment developed by the community. Putting it in simple words, we could say they are a collection of scripts that define a new set of functions, data type and methods that allow further manipulation of our data. Because the architechture of all of this packages is highly interlinked, it is easy to run into incompatibilities installing our packages. 

That's why Python distributors like [Anaconda](https://www.anaconda.com/download) become useful, particularly because it allows us to install [Conda](https://conda.io/projects/conda/en/latest/user-guide/getting-started.html), which is a very powerful package and environment manager. In particular, when we use conda to install a package it downloads a version of the package that has already been compiled for our specific operating system and architecture. Furthermore, Conda resolves package dependencies automatically, avoiding conflicts and installation failures. It also enables users to create isolated environments for projects, ensuring clean and reproducible development environments.

To make sure we all have the same working environment, we will follow the installation guideline provided by Joël. After you have downloaded Anaconda and VSCode and Anaconda, we download the environment configuration file (https://datascience.joelmarbet.com/environment.yml). Environment files (with the .yml extension) are files that contain all the dependencies and settings for a Conda environment. This file allows users to recreate the exact environment with all necessary dependencies by simply running a comand on the Conda terminal, making it easier to share and reproduce environments across different systems.
This means that if we all install the same configuration file, we will be sharing the same conda computational environment (i.e., same packages, versions, environment name). Just to review the instructions:

1. After downloading Anacona and the `environment.yml` file, we open a terminal (Mac) or the Anaconda Terminal (Windows)

2. We change the directory to the folder where we have stored the downloaded file by typing `cd path/to/environment`, where `path/to/environment` is the folder containing the environment configuration file.

3. To create the environment we type: `conda env create -f environment.yml` 

4. We check the installation by activating the environment: `conda activate datascience_course_cemfi`.

5. We test the Python version: `python --version`. 

In VSCode, we have to make sure we have downloaded all the relevant extensions and then, we open a new notebook, we should be able to select the new environment to run our code. 

# **2. Jupyter Notebooks**

<hr>

<img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fkiran-parte.github.io%2Faiforall%2Fassets%2Fimages%2Fblog%2Fjupyter.jpg&f=1&nofb=1&ipt=9a8eccb2a29542fc1212ab390ec49132d105b54180f259a57faab1bacaf1c5f5
" width="200px" />

The way in which we will interact with Python code will be through Jupyter Notebooks on VSCode.  Jupyter Notebooks, as well as the popular Jupyter Lab, are all part of the [**Jupyter Project**](https://jupyter.org/try) which revolves around the provision of tools and standards for interactive computing across different computing languages (**Ju**lia,**Pyt**hon,**R**) through computational notebooks.

Jupyter Notebooks is an example of **computational notebook**. Notebooks merge code, plain language explanations, data, and visualizations into a shareable document. A notebook offers a rapid interactive platform for code typing, data exploration, visualization, and idea sharing, stemming from the belief that the most effective way to learn and program is through hands-on interaction with code. That is, we can pool together in a single file (**a notebook**) all data workflow behind our analysis. 

At the end of the day, notebooks capture interactive session inputs and outputs along with explanatory text providing a comprehensive computational record. The notebook file, saved with the .ipynb extension, is internally JSON files, allowing for version control and easy sharing. Additionally, notebooks can be exported to various static formats. 

Notebooks replace the traditional console-based interactive computing by introducing a web-based application that captures the entire computation process: from code development and documentation to execution and result communication. The Jupyter notebook integrates both elements:

1. **A web application** (although we will use VSCode rather than the browser based extension): This browser-based editing program enables interactive authoring of computational notebooks, offering a swift environment for code prototyping, data exploration, visualization, and idea sharing.

2. **Computational Notebook documents**: These shareable documents combine computer code, plain language explanations, data, visualizations and interactive controls.

The Jupyter notebook interacts with kernels, which are implementations of the Jupyter interactive computing protocol specific to different programming languages. In plain words, *kernels* are the separate process that interprets and executes our code in a given programming language. 

From Jupyter on VSCode we can just open a new Jupyter Notebook on **File** &rarr; **New File**  &rarr; **Jupyter Notebook**. When we open a new notebook, we will find the following elements:

![Notebooks on VSCode](https://raw.githubusercontent.com/albaminanomanero/intro-python/main/img1.png)

1. Toolbar of VSCode. 
2. Name of our new notebook: notice that when a white point appears is because there are unsaved changes. Notice that notebooks have the **.ipynb** extension. 
3. Run all: will run all cells of the notebook sequentially. 
4. Kernel: allows to specify the kernel in which we want to run our notebook. 
5. Notebook toolbar: allows to run and edit cells. 
6. Indicator of type of cell (Python or markdown)
7. Cell
8. Add new cells 

The notebook is composed of a series of cells, each serving as a multiline text input field. These cells can be executed by pressing Shift-Enter, or by clicking the "Play" button in the toolbar or selecting "Cell" then "Run" from the menu bar. The behavior of cell execution depends on its type, with three main types: code cells, markdown cells, and raw cells. While every cell begins as a code cell, its type can be altered using a drop-down menu in the toolbar, which will be activated if you press  on the type of cell in the bottom-left corner (i.e., in the image below where it says Python.)

![Notebooks on VSCode](https://raw.githubusercontent.com/albaminanomanero/intro-python/main/img3.png)

**Main types of cells**:
- Code

    Allow editing and creating new code, complete with syntax highlighting and tab completion. The choice of programming language depends on the kernel, with the default kernel (IPython) executing Python code.

    Upon execution of a code cell, the resulting computation outputs are then showcased in the notebook as the cell's output. This output isn't limited to text; various forms such as matplotlib figures and HTML tables (as employed in packages like pandas for data analysis) are also supported. 

- Markdown: 

    Allow you to document the computational process in a literate manner, combining descriptive text with code using rich text. In IPython, this is achieved by using Markdown cells, where text is marked up with the Markdown language. Markdown provides a simple way to emphasize text, create lists, and structure the document using headings indicated by hash signs. Markdown headings become clickable links in the notebook and provide structure hints when exporting to other formats like PDF. When a Markdown cell is executed, the Markdown code is converted into formatted rich text, allowing for arbitrary HTML code for further formatting.

- Raw cells: 

    They allow to write output directly, meaning they are not evaluated by the kernel when runing the notebook

**Workflow:**

A workflow in a Jupyter Notebook is run sequentially. As in a script, there is line hierarchy within cells, and there is also sequential hierarchy between cells. However, notebooks have the advantage of allowing us to edit cells separately multiple times until achieving the desired outcome, rather than rerunning separate scripts.

When working on a computational problem, you can organize related ideas into cells and progress incrementally, moving forward once previous parts function correctly, which is very useful when running codes that have snippets that take long. If at anypoint we want to interrupt running a cell, we can achieve that pressing the interrupt cell. Also, we can restart the Kernel to shut down the computational process. 

When we run a cell, the notebook sends that process to the Kernel and prints directly the output of the execution. The execution order appears in square brackets to the left of the printed output. Notice that when we run a notebook, all cells are run in the same kernel. This means that whatever we run in a given cell will remain active unless we restart the Notebook. 

Also, whenever we shut down a Notebook (either by restarting the Kernel or just saving and closing the notebook), all of our processes and outputs that have not been saved to disk will be erased. 

> My tip: while notebooks are highly useful for writing and explaining work processes, particularly for others, they may not be as practical for large research projects. Instead, I often work concurrently on a script that I run in a notebook, executing it step by step until all lines of code run smoothly. Once I have finished the code, I only save the script. 

# **3. Preliminaries**

<hr>

## **3.1. Introduction to Markdown**

double-click in a Markdown cell to edit it. 

- **Headings**
    - Use hash signs to create headings, with the number of hash signs indicating the heading level:
    - `# Heading 1`, `## Heading 2`, ... `###### Heading 6`

- **Italics**
    - Surround text with single asterisks or underscores: `*italic*` or `_italic_`
    - *This is some example text in italics*

- **Bold**
    - Surround text with double asterisks or underscores: `**bold**` or `__bold__`
    - **This is some example text in bold**
- **Blockquotes**
    - Start a line with a greater-than sign: `> This is a blockquote`
    - > This is an example blockquote


- **Code**
    - Inline code:
        - Surround code with backticks: `` `code` ``
        - `print("This is an example inline code")`
    - Code block:
        - Surround code with triple backticks and specify the language: 
        ````
        ```python
        Your code here
        ```
        ````
        - For example:
     ```python
     # This is an example code block
        def hello_world():
            print("Hello, world!")
     ```

## **3.2. Running code**

In a Jupyter Notebook you can execute a code cell by using one of the following methods:

- **[Option 1]** Click the ▶️ button in the toolbar of the cell you want to run (top left corner of the cell)

- **[Option 2]** Keyboard shortcut: Click on the cell you want to run & press [`⇧` shift] + [`⏎` enter] 


> **Recommendation**: Use the keyboard shortcut to run code cells, as it is faster than clicking the button. Also, note that if you leave [`⇧` shift] pressed and press [`⏎` enter] multiple times, you will run cells sequentially.

In [68]:
print("Hello, world!")

Hello, world!


## **3.3. Commenting code**

Commenting code is useful for adding explanations or notes within the code without affecting its execution.

- In Python, comments are created by adding a `#` symbol before the text you want to comment. 
- Also, you can create multi-line comments by enclosing the text in triple quotes (`"""` or `'''`).



> **Recommendation**: use keyboard shortcuts to comment and uncomment code (uses `#` by default)

| Platform        | Keyboard Shortcut                                 |  
|-----------------|------------------------------------------|  
| Mac             | [`⌘` command] + [`⇧` shift] + [`/`]      |  
| Windows/Linux   | [`Ctrl`] + [`/`]                         |  


In [69]:
print("Hello, world!")  # This line prints a `Hello, world!` message

Hello, world!


In [70]:
# # The line below is commented and won't execute, try removing the # to see it in action
# print("I want to be executed, but the # in front won't let me!!!") 

In [71]:
"""
This is a multi-line comment.
It can span multiple lines.
You can use it to explain complex logic or provide documentation.
You can also use it to temporarily disable code.
"""

'\nThis is a multi-line comment.\nIt can span multiple lines.\nYou can use it to explain complex logic or provide documentation.\nYou can also use it to temporarily disable code.\n'

## **3.4. Printing**

- `print()`
    - To display output in Python, you can use the `print()` function. 
    - This function takes one or more arguments and prints them to the output cell. 
    - You can print strings, numbers, variables, and even complex data structures like lists or dictionaries.

In [72]:
print("Hello, world!")           # Print a string
print(42)                        # Print a number

Hello, world!
42


In [73]:
name = "Alice"
number = 4
color = "blue"

print("My name is", name, ", my favorite number is", number, "and my favorite color is", color) # Print multiple things together

My name is Alice , my favorite number is 4 and my favorite color is blue


In [74]:
numbers = [1, 2, 3, 4, 5]
print("List:", numbers)       # Print a list

dictionary = {"Joel": "BdE", "Jesus": "cemfi"}
print("Dictionary:", dictionary)  # Print a dictionary

List: [1, 2, 3, 4, 5]
Dictionary: {'Joel': 'BdE', 'Jesus': 'cemfi'}


- **f-strings for Formatted Output**
    - Python’s f-strings provide a convenient way to embed variables and expressions inside string literals. 
    - Just add an `f` before the string and use curly braces `{}` to include variables or expressions.
    - It's essentially the same as using concatenation within `print()`, but allows for more readable and formatted output.


In [75]:
# Print using regular string concatenation
print("My name is", name, ", my favorite number is", number, "and my favorite color is", color)

# Print using f-string
print(f"My name is {name} , my favorite number is {number} and my favorite color is {color}.")

My name is Alice , my favorite number is 4 and my favorite color is blue
My name is Alice , my favorite number is 4 and my favorite color is blue.


In [76]:
name = ["Jesus", "Joel"]
adj1 = ["cool", "boring"]
adj2 = ["much", "little"]
number = [10, 0]

i = 0
print(f"{name[i]} is such a {adj1[i]} teacher... I am learning so {adj2[i]} that I will get a {number[i]} in the exam!")

Jesus is such a cool teacher... I am learning so much that I will get a 10 in the exam!


# **4. Basics of Python syntax**

<hr>

Python syntax is determined by the fact that:

- Python is an interpreted language. By this we mean, that the Python interpreter will run a program by executing and evaluating one line at a time and in a sequential manner. That is, the source code is executed by interpreter line-by-line, without the need for compilation into machine code beforehand

- Python is an **O**bject-**O**riented **P**rogramming (OOP) language. Everything we define in our code exists within the interpreter as Python object, meaning it will have its associated **attributes** and **methods**. 

    - **Attributes** are values associated with an object, they are defined by the class of an object. 
        - Typically, we call objects with the syntax `object.attribute_name`.

    - **Methods** are functions associated with objects, which can access the attributes of the object. 
        - Typically, we use methods with the syntax `object.method_name()`.

In [77]:
x = 5.1 + 2j
print('What part of X is real?', x.real) # This is an attribute of the variable x 
print('What part of X is complex?', x.imag) # This is an attribute of the variable x

What part of X is real? 5.1
What part of X is complex? 2.0


In [78]:
real_part = x.real
print('Is `real_part` an integer?', real_part.is_integer()) # .is_integer() is a method 

Is `real_part` an integer? False


In [79]:
print('What type of variable is x?', type(x)) # type() is a function
print('What type of variable is real_part?', type(real_part)) # this is a function

What type of variable is x? <class 'complex'>
What type of variable is real_part? <class 'float'>


In [80]:
x = "Hello"
x.lower()

'hello'

## **4.1 Creating variables**

> Nothing prevents Python from rewriting variables. So if we first do `x=5` and then `x=6` we will automatically rewrite the variable `x` to 6. 

Variables allow us to define names for objects we will store in memory and use in our program. This call by object reference system implies that after we assign the name to an object, we can access the object by that reference name. For instance, `'x'` above is referencing to the memory object that is storing `5.2`. We can create a new variable `x2` that contains the same elements as `x`: 

In [81]:
x = 2
y = x
x

2

Both variables are the same, because they are both refering to the same memory object. However, because numbers are inmutable objects, changes to one won't affect the other. 

In [82]:
x = x + 5
print("This is 'x' after we sum 5 to it:", x)
print("This is our originary 'y', which hasn't changed", y)

This is 'x' after we sum 5 to it: 7
This is our originary 'y', which hasn't changed 2


> Operation signs: additions(`+`), substractions(`-`), multiplication (`*`), division (`/`), exponent(`**`), remainder of division aka modulo (`%`)

Immutable objects are also *strings* and *tuples* (more on this later), but there are also mutable objects like *lists*. 

<span style="color:red"> In the case of **mutable objects**, if we create two variables that are just referencing the same, changing one **will affect** the other because both variables refer to the same memory object that has been modified.  </span>

In [83]:
y = ['abc','def']
y2 = y
y2.append('ghi')

print("This is 'y2' variable after we add a new string:", y2)
print("This is our originary 'y': ", y)

This is 'y2' variable after we add a new string: ['abc', 'def', 'ghi']
This is our originary 'y':  ['abc', 'def', 'ghi']


We can also assign variable names to different objects in the same code line separating them through commas. 

In [84]:
one, two, three = 'abc', 'def', 'ghi'
print(f"{one = }")
print(f"{two = }")
print(f"{three = }")

one = 'abc'
two = 'def'
three = 'ghi'


## **4.2 Naming variables: good practices**

Just as in writing regular text, coding also involves an idyosincratic coding style that often results in differences between two individuals' code, even if they are accomplishing the same task or using the same functions. This divergence is especially noticeable in variable naming. However, whether we are more of a concise or descriptive type, there are some rules and good practices for everyone: 
1. Names can only contain upper and lower case letters, underscores (_), numbers. 
    > Important: Python is case sensitive, which means that variables with different capitalization are considered distinct (i.e., `Abc`, `abc` and `ABC` are all different)
2. Names can never start with a digit number, only letters or underscore. 
3. They cannot be **keywords** (Python language reserved words).
4. We typically use only lower case letters for variables, and reserve upper case letters for parameters or constants. 
5. Names should be self-explaining and balance out brevity and explicability. Typically, we reserve names for variables, verbs for attributes, adjectives for booleans.
6. We can use names in any language, but in general English is preferred so that anyone could follow the code.
7. Avoid using built-in function names because that will overwrite the function (i.e., if we write `type` we will no longer be able to use `type` to access the `type' of variables).

In [85]:
# False = 1 # This would throw a SyntaxError

In [86]:
import keyword

# Get all Python keywords
keywords = keyword.kwlist

print("Python keywords (don't use any of these words to name a variable!):")
for kw in keywords:
    print(f"- {kw}")


Python keywords (don't use any of these words to name a variable!):
- False
- None
- True
- and
- as
- assert
- async
- await
- break
- class
- continue
- def
- del
- elif
- else
- except
- finally
- for
- from
- global
- if
- import
- in
- is
- lambda
- nonlocal
- not
- or
- pass
- raise
- return
- try
- while
- with
- yield


## **4.3 Data types**

Unlike some other programming languages, Python dynamically infers the type of a variable based on the assigned value. We can access the type of variables using the `type()` function. 

### **4.3.1. Primitive data types**

Primitive data types are: `strings`, `integers`, `floats`, `booleans`, `None`. 

<!--- While I am hard-coding some examples for booleans,  it's more common for them to be generated as the outcome of assessing a condition within a function (i.e., Am I Jesus? True). In fact, booleans are typically obtained by comparisons and can be manipulated with logical operations (`and`, `not`, `or`)
---> 

In [87]:
this_is_int = 5
type(this_is_int)

int

In [88]:
this_is_float = 5.2
type(this_is_float)

float

In [89]:
this_is_string = 'abc'
type(this_is_string)

str

In [90]:
this_is_bool = True
type(this_is_bool)

bool

In [91]:
# More booleans examples
print('5 > 3\t', 5 > 3)      
print('5 > 5\t', 5 > 5)       
print('5 != 4.9', 5 != 4.9)

5 > 3	 True
5 > 5	 False
5 != 4.9 True


In [92]:
this_is_None = None
type(this_is_None)

NoneType

### **4.3.2 Container data types**

Besides the **primitive datatypes**, there are also **containers datatypes** which are a collection of objects in a particular given structure. They can be tuples, lists or dictionaries. 

\- **Tuples**: fixed sequence of <span style="color:red"> **immutable** </span> python objects. They are defined as a sequence of elements, separated by a comma between brackets (`()`) and can mix primitive data types. 

In [93]:
this_is_tuple = (0,1,2,3,4,5,6)
this_is_tuple_str = ('a','b','c')
this_is_tuple_mix = (2,'b',True)
this_is_nested = ('a',(2,3,4),this_is_tuple_mix)

print(type(this_is_tuple), type(this_is_tuple_str), type(this_is_tuple_mix), type(this_is_nested))

<class 'tuple'> <class 'tuple'> <class 'tuple'> <class 'tuple'>


We can acces its elements using indexing, which we call as `name_of_tuple[i]`, where `i` indicates the position of the element we want. 
- From left to right, <span style="color:orange"> we start counting from `0`  </span>
- From right to left, <span style="color:orange"> we start counting from `-1` </span>

In [94]:
this_is_tuple = (0,1,2,3,4,5,6)

print(f"First element is {this_is_tuple[0]}")
print(f"Second element is {this_is_tuple[1]}")

print(f"Last element is {this_is_tuple[-1]}")

First element is 0
Second element is 1
Last element is 6


To index a range of elements, we can use the syntax `name_of_tuple[i:j]`, which will return all elements from `i` to `j-1`.

In [95]:
this_is_tuple[0:2]

(0, 1)

> Notice that for Python, the `=` is not the mathematical equality sign. It simply establishes an assignment saying left-hand side is right-hand side. When we want to make comparisons to check equality, we use `==`. 

For example, if we want to check whether the two tuples below are equal
```python
this_is_tuple = (0,1,2,3,4,5,6)
this_is_tuple_str = ('a','b','c')
```
we do:

In [96]:
print(this_is_tuple == this_is_tuple_str)

False


Tuples are immutable. Immutability means that once created, their elements cannot be change (*they don't support item assignment*)

In [97]:
# t = (1, 2, 3)
# t[0] = 10  # This would raise a TypeError

In [98]:
# t.append(4)  # This would raise an AttributeError

While tuples are immutable, we can operate with them in different ways. We can concatenate them using the `+` sign, we can repeat them a n number of times using `*n*`, and we can unpack them. 

In [99]:
print(this_is_tuple + this_is_tuple_str + this_is_tuple_mix) # concatenating

(0, 1, 2, 3, 4, 5, 6, 'a', 'b', 'c', 2, 'b', True)


In [100]:
print(this_is_tuple_mix*3) # repeating 

(2, 'b', True, 2, 'b', True, 2, 'b', True)


In [101]:
unpack1, unpack2, unpack3 = this_is_tuple_str # unpack 
print(unpack1)

a


In [102]:
*_ , only_third_e = this_is_tuple # unpack. Note: if we use `*_` in the unpack, we will discard some elements
print(only_third_e)

6


\- **Lists**: modifiable sequence of <span style="color:green"> **mutable** </span> Python objects (i.e., a tuple that we can change). They are also defined as a comma separated sequence of elements, but differently from tuples, with square brackets (`[]`)

In [103]:
this_is_list = [1,2,3]
print(this_is_list)

[1, 2, 3]


We can slice them in the same way as tuples. 

In [104]:
print(this_is_list[2]) # 3rd element
print(this_is_list[0:2]) # starts at 0, ends at 2-1 (i.e., 1 which is the second element)

3
[1, 2]


We can:
 - **add** elements using `append()` 
 - **insert** elements in specific positions using `insert(positions,what we want to insert)`
 - **modify** elements using `name_of_list[i] = new_value`
 - **remove** elements using `remove(what we want to remove)` or `pop(i)`, which removes the element at position `i` and returns it.
    - Note: `remove()` will remove the first occurrence of the element, while `pop()` will remove the element at the specified index and return it. If no index is specified, `pop()` removes and returns the last item in the list.

In [105]:
# Adding elements to a list
this_is_list = [1,2,3]

this_is_list.append('this teacher is so fun') # This will add the string to the end of the list
print(this_is_list)

[1, 2, 3, 'this teacher is so fun']


In [106]:
# Inserting elements at a specific position
this_is_list = [1,2,3]

this_is_list.insert(2,'hello')  # let's insert 'hello' as the second element
print(this_is_list)

[1, 2, 'hello', 3]


In [107]:
# Removing elements from a list using `pop``
this_is_list = [1,2,3]

this_is_list.pop(2) # This will remove the third element (index 2) of the existing list, which is [1,2,3]
print(this_is_list)

this_is_list.pop() # This will remove the last element of this_is_list, which now is [1,2]
print(this_is_list)

[1, 2]
[1]


In [108]:
# Removing elements from a list using `remove`
this_is_list = ['a', 'b', 'c', 'a', 'b', 'c']

this_is_list.remove('a') # This will remove the first occurrence of 'a'
print(this_is_list)

['b', 'c', 'a', 'b', 'c']


\- **Dictionaries**: unordered collection of items. Items consist on pairs of Python objects named keys and values. Each key is associated with a unique value, like in a dictionary entry, which allows us to access, retrieve and modify its values. Dictionaries are typically created using curly braces as 

```python 
dictionary = {
        key1 : value1, 
        key2 : value2,
        ...
        keyN : valueN
}
```

In [109]:
weekday_activities = {
    "Monday": ["Go to work", "Attend meetings", "Exercise", "Cook dinner"],
    "Tuesday": ["Work on projects", "Run errands", "Visit the gym"],
    "Wednesday": ["Work remotely", "Attend class", "Grocery shopping"],
    "Thursday": ["Client meetings", "Volunteer", "Cook dinner"],
    "Friday": ["Finish work tasks", "Meet friends for dinner", "Movie night"],
}

print(weekday_activities)

{'Monday': ['Go to work', 'Attend meetings', 'Exercise', 'Cook dinner'], 'Tuesday': ['Work on projects', 'Run errands', 'Visit the gym'], 'Wednesday': ['Work remotely', 'Attend class', 'Grocery shopping'], 'Thursday': ['Client meetings', 'Volunteer', 'Cook dinner'], 'Friday': ['Finish work tasks', 'Meet friends for dinner', 'Movie night']}


To access one of the elements, we can look for the corresponding key. 

In [110]:
weekday_activities['Monday']

['Go to work', 'Attend meetings', 'Exercise', 'Cook dinner']

We can also obtain all keys and values, through methods `keys()`, `values()`, `items()`. The results of these methods, although they migh seems like lists, cannot be subscripted. 

In [111]:
print(weekday_activities.keys())

# weekday_activities.keys()[0] # This will raise a TypeError because keys() returns a view object, not a list

dict_keys(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'])


In [112]:
print(weekday_activities.values())

# weekday_activities.values()[0] # This will raise a TypeError because values() returns a view object, not a list

dict_values([['Go to work', 'Attend meetings', 'Exercise', 'Cook dinner'], ['Work on projects', 'Run errands', 'Visit the gym'], ['Work remotely', 'Attend class', 'Grocery shopping'], ['Client meetings', 'Volunteer', 'Cook dinner'], ['Finish work tasks', 'Meet friends for dinner', 'Movie night']])


In [113]:
print(weekday_activities.items())

# weekday_activities.items()[0] # This will raise a TypeError because items() returns a view object, not a list

dict_items([('Monday', ['Go to work', 'Attend meetings', 'Exercise', 'Cook dinner']), ('Tuesday', ['Work on projects', 'Run errands', 'Visit the gym']), ('Wednesday', ['Work remotely', 'Attend class', 'Grocery shopping']), ('Thursday', ['Client meetings', 'Volunteer', 'Cook dinner']), ('Friday', ['Finish work tasks', 'Meet friends for dinner', 'Movie night'])])


We can add new entries by specifying a new key and value pair. 

In [114]:
weekday_activities['Saturday'] = 'Fondue night'
weekday_activities

{'Monday': ['Go to work', 'Attend meetings', 'Exercise', 'Cook dinner'],
 'Tuesday': ['Work on projects', 'Run errands', 'Visit the gym'],
 'Wednesday': ['Work remotely', 'Attend class', 'Grocery shopping'],
 'Thursday': ['Client meetings', 'Volunteer', 'Cook dinner'],
 'Friday': ['Finish work tasks', 'Meet friends for dinner', 'Movie night'],
 'Saturday': 'Fondue night'}

It is also possible to use `.update()` to add new entries and modify other.

In [115]:
weekday_activities.update({'Friday':'Birthday Party', 'Sunday':'Hike'})
weekday_activities

{'Monday': ['Go to work', 'Attend meetings', 'Exercise', 'Cook dinner'],
 'Tuesday': ['Work on projects', 'Run errands', 'Visit the gym'],
 'Wednesday': ['Work remotely', 'Attend class', 'Grocery shopping'],
 'Thursday': ['Client meetings', 'Volunteer', 'Cook dinner'],
 'Friday': 'Birthday Party',
 'Saturday': 'Fondue night',
 'Sunday': 'Hike'}

Notice, however that if we already have an entry with a given key and we perform a new assign, we will overwrite it. 

In [116]:
weekday_activities['Friday']='Cinema'
weekday_activities

{'Monday': ['Go to work', 'Attend meetings', 'Exercise', 'Cook dinner'],
 'Tuesday': ['Work on projects', 'Run errands', 'Visit the gym'],
 'Wednesday': ['Work remotely', 'Attend class', 'Grocery shopping'],
 'Thursday': ['Client meetings', 'Volunteer', 'Cook dinner'],
 'Friday': 'Cinema',
 'Saturday': 'Fondue night',
 'Sunday': 'Hike'}

We can again use `pop` to remove elements specifying a key. Equivalently, we can use `del` to remove an entire entry. 

In [117]:
weekday_activities.pop('Monday')
weekday_activities

{'Tuesday': ['Work on projects', 'Run errands', 'Visit the gym'],
 'Wednesday': ['Work remotely', 'Attend class', 'Grocery shopping'],
 'Thursday': ['Client meetings', 'Volunteer', 'Cook dinner'],
 'Friday': 'Cinema',
 'Saturday': 'Fondue night',
 'Sunday': 'Hike'}

In [118]:
del weekday_activities['Tuesday']
weekday_activities

{'Wednesday': ['Work remotely', 'Attend class', 'Grocery shopping'],
 'Thursday': ['Client meetings', 'Volunteer', 'Cook dinner'],
 'Friday': 'Cinema',
 'Saturday': 'Fondue night',
 'Sunday': 'Hike'}

Using `items()` we can iterate through each entry in the dictionary. To do this, for each entry, we unpack the two elements that appear in the tuple generated by `.items()`

In [119]:
for day, activity in weekday_activities.items():
    print('My schedule for', day, 'is', activity)

My schedule for Wednesday is ['Work remotely', 'Attend class', 'Grocery shopping']
My schedule for Thursday is ['Client meetings', 'Volunteer', 'Cook dinner']
My schedule for Friday is Cinema
My schedule for Saturday is Fondue night
My schedule for Sunday is Hike


Also, if he have a collecion of keys and values, we can write them as a dictionary using .`zip(k,v)`. This will automatically assign the keys to the values in an ordered manner (i.e., first element of the key list cooresponds to first element of the value list).

In [120]:
bday_dict = {} # initialize empty 
key_list = ('30_November','14_December')
value_list= ("Joël's birthday", "Jesus' birthday")

for key, value in zip(key_list, value_list):
    bday_dict[key] = value
    
bday_dict

{'30_November': "Joël's birthday", '14_December': "Jesus' birthday"}

## **4.4 Functions**

Sometimes we find that our code is repeating the same few lines multiple times, or we are sharing the same lines in different scripts. **Functions** in Python allow us to encapsulate a set of instructions and reuse them throughout our code. This helps us avoid repeating the same code multiple times and makes our code more organized and easier to maintain, while the complexity of the function is abstracted away. 

In essence, functions contains three elements: the arguments, the commands we execute on them (i.e., the body of the function), and the return values. They have the following structure: 
```python
def function_name(arg1, arg2):
    # do something with argument 1 and argument 2 to get the result r3
    return r3
```

It is also possible to avoid returning anything by specifying ```return None```  or nothing at all or even use `print()` expressions. 

In [121]:
import numpy as np

def function_with_return(x,y):
    return x+y

def function_with_print(x,y):
    print(x+y)

In [122]:
function_with_return(4,6)

10

In [123]:
r1 = function_with_return(4,6)

In [124]:
print(r1)

10


In [125]:
function_with_print(4,6)

10


In [126]:
r2 = function_with_print(4,6)

10


In [127]:
print(r2)

None


Although a function can have **multiple outputs returned**, it cannot have more than one `return` line (unless they are part of some conditions) because the function stops evaluating the code after it reaches the first `return`. 

In [128]:
def returns_two_vars(x,y):
    return x+y,x*y

returns_two_vars(3,5)

(8, 15)

And we could access them with our unpacking strategy

In [129]:
r1,r2=returns_two_vars(3,5)
print('r1:', r1)
print('r2:', r2)

r1: 8
r2: 15


In [130]:
def returns_two_vars(x,y):
    return x+y
    # return x*y # This return statement will not be evaluated. The function will exit after the first return statement is executed.
    # return x**y

Notice if we call as argument a variable that has been defined outside the function, it will automatically take that value (i.e., it's *global* to the function). If the variable is also defined inside, it will be *local* within the function.

In [131]:
global_var = 1

def silly_function(input_var):
    local_var = 2
    output_var = global_var + local_var + input_var
    return output_var

In [132]:
output_var = silly_function(3)
output_var

6

In [133]:
global_var

1

In [134]:
# input_var # This would raise a NameError because input_var is not defined outside the function

In [135]:
# local_var # This would raise a NameError because local_var is inputted to the function, but has not been defined outside the function

In [136]:
global_var = 'I am a GLOBAL variable and I am defined outside the function!'

def silly_function(input_var):
    
    local_var = '\nI am a LOCAL variable and I am **only** defined inside the function!'
    
    print(global_var + local_var + input_var)
    
    output_var = "I am an OUTPUT variable and I am returned by the function!"
    
    return output_var

In [137]:
output_var = silly_function('\nI am an INPUT variable and I am passed to the function!')

I am a GLOBAL variable and I am defined outside the function!
I am a LOCAL variable and I am **only** defined inside the function!
I am an INPUT variable and I am passed to the function!


In [138]:
output_var

'I am an OUTPUT variable and I am returned by the function!'

## **4.5 Control flow: branching and looping**
Every script, and computer programs in general, consist of instructions that are executed sequentially from "top" to "bottom". This sequence is what we know as flow. It's possible to modify this sequential flow to include branching or repeating certain instructions. The statements that allow us to make these modifications are grouped under flow control. 

### **4.5.1  Branching: `if`, `elif`, `else`**

Branching refers to the capacity to make decisions and execute distinct sets of statements depending on whether one or more conditions are met. In Python, branching departs from the `if` statement. 

```python
if condition:
    do line1
    do line2
```

- If `condition` is found to be true, the code will perform `line1` and `line2`. 
- The way Python understands `line1` and `line2` are associated with the if statement is because of *identation* (i.e., white space to the left of the beginning of a line). 
    - The 4 spaces from the left to where `do line1` is written constitute the Python ident. 
    - We can use the `tab` key to get the ident and `shift+tab` to remove one ident. 
    - Idents are cumulatives, so if we had two blocks, the lines within the second would have to have two idents. 

For instance, the line below would perform `line1` only if the condition is true, and after it would perform `line2` for all cases. 

```python
if condition:
    do line1
    
do line2
```

In [139]:
month = 'February'
if (month=='January') or (month=='February'):
    print('Hey! you are in the indented block')
    print('The entire month of', month, 'is considered to be in Winter')

print(month, 'is a month of the year')

Hey! you are in the indented block
The entire month of February is considered to be in Winter
February is a month of the year


In [140]:
month = 'June'
if (month=='January') or (month=='February'):
    print('Hey! you are in the indented block')
    print('The entire month of', month, 'is considered to be in the winter')

print(month, 'is a month of the year')

June is a month of the year


But what if we still want our branch to do something when the first condition is not met? We can achieve this by specifying a new action with `else`:
```python
if condition1:
    do line1
else:
    do line2
```
Notice that, whenever condition1 is not true, the `else` condition will imply we perform line2. 

In [141]:
month = 'January'

if (month=='January') or (month=='February'):
    print('Hey, you are in the indented block')
    print('The entire month of', month, 'is considered to be in the winter')
else: 
    print('The entire month of', month, 'is NOT considered to be in the winter')

Hey, you are in the indented block
The entire month of January is considered to be in the winter


We can also be more specific and chain conditions using `elif`. This will start executing the first condition, if it is not true, it will try the second and so on and so forth. Once it has found a condition for which it is `True` it will execute the lines under it and will stop evaluating the rest of conditions. This means that at most one - the first encountered- `True` statement will be evaluated. 

In [142]:
month = 'May' # Try December!
if (month=='January') or (month=='February'):
    print('Hey, you are in the indented block 1')
    print('The entire month of', month, 'is considered to be in the winter')
elif (month=='April') or (month=='May'): 
    print('Hey, you are in indented block 2')
    print('The entire month of', month, 'is considered to be in the spring')
elif (month=='July') or (month=='August'): 
    print('Hey, you are in indented block 3')
    print('The entire month of', month, 'is considered to be in the summer')
elif (month=='October') or (month=='November'): 
    print('Hey, you are in indented block 4')
    print('The entire month of', month, 'is considered to be in the autumn')
else:
    print('Hey, you reached the else')
    print('The month', month, 'is in between two different seasons')    

Hey, you are in indented block 2
The entire month of May is considered to be in the spring


If we want a statement to do nothing in Python, we use the pass keyword. This is because Python does not allow an empty block within a conditional statement. It's akin to being at a crossroads where we have to choose between turning left or right, but instead, we decide to wait and take no action.

In [143]:
month = 'April'
if (month=='January') or (month=='February'):
    print('Hey, you are in the idented block 1')
    print('The entire month of', month, 'is considered to be in the winter')
elif (month=='April') or (month=='May'): 
    pass
elif (month=='July') or (month=='August'): 
    print('Hey, you are in idented block 3')
    print('The entire month of', month, 'is considered to be in the summer')
elif (month=='October') or (month=='November'): 
    print('Hey, you are in idented block 4')
    print('The entire month of', month, 'is considered to be in the autumn')
else:
    print('Hey, you reached the else')
    print('The month', month, 'is in between two different seasons')    

### **4.5.2  Looping: `while`, `for`**

Sometimes, we also want to repeat the same statement multiple times. This is what we mean when we refer to `iteration` or `looping`, which we achieve in python through `while` and `for`. 

\- **While** loops execute a statement whenever the condition is true. We typically use this kind of loop to perform some operation or update in the variable. 
```python
while condition:
    do this
```

In [144]:
good_morning='Y'
while good_morning == 'Y':
    print('Good morning, Joël!')
    print('Good morning, Jesús!')
    good_morning = input('Do we keep saying good morning? [Y/N]')
print('Awesome! Enjoy your class')

Good morning, Joël!
Good morning, Jesús!
Awesome! Enjoy your class


Notice that the previous loop can go on and on until we press N. Also, if we remove the line `good_morning = input('Do we keep saying good morning? [Y/N]')` it would just keep going and going. That's why typically in while loops we update the variable to make sure we stop when we reach a given amount of iterations. 

In [145]:
good_morning='Y'
iteration=0
while good_morning == 'Y':
    print("Iteration:", iteration)
    print('Good morning, Joël!')
    print('Good morning, Alba!')
    print('-'*10)
    iteration += 1
    if iteration==5:
        break

Iteration: 0
Good morning, Joël!
Good morning, Alba!
----------
Iteration: 1
Good morning, Joël!
Good morning, Alba!
----------
Iteration: 2
Good morning, Joël!
Good morning, Alba!
----------
Iteration: 3
Good morning, Joël!
Good morning, Alba!
----------
Iteration: 4
Good morning, Joël!
Good morning, Alba!
----------


- **For**: we use `for` loops when we want to iterate over elements of a sequence. 

In [146]:
for letter in "cemfi":
    print(letter.upper())
    print("...")

C
...
E
...
M
...
F
...
I
...


In [147]:
months_of_year = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
summer_holidays = ["June", "July", "August"]
winter_holidays = ["December"]

# Loop through the months and add some summer vibes
for month in months_of_year:
    if month in winter_holidays:
        print(f"- {month} = Christmas, Christmas, Christmas!") 
    elif month in summer_holidays:
        print(f"- {month} = Escape from Madrid if you can!")
    else:
        print(f'- {month} = work, work, work')

- January = work, work, work
- February = work, work, work
- March = work, work, work
- April = work, work, work
- May = work, work, work
- June = Escape from Madrid if you can!
- July = Escape from Madrid if you can!
- August = Escape from Madrid if you can!
- September = work, work, work
- October = work, work, work
- November = work, work, work
- December = Christmas, Christmas, Christmas!


We can use the function `range` also to get a sequence of number to loop over. It follows the syntax `range(start, stop, step)`:
- **Start**
    - Where the sequence starts: it includes the start value (first number will always be `start`)
    - Optional 
    - Defaults to 0 (unless otherwise specified)
- **Stop**:
    - Where the sequence ends: it does not include the stop value (last number will always be `stop`-`step`)
    - Required field
- **Step**: 
    - Step size of the sequence, i.e., how much we increase the value at each iteration: `start + step`, `start + 2*step`, `start + 3*step`, ...
    - Optional
    - Defaults to 1 (unless otherwise specified)

In [148]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [149]:
for i in range(1,10,2):
    print(i)

1
3
5
7
9


# **5. Introduction to `NumPy`**

<hr>

<img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fuser-images.githubusercontent.com%2F1217238%2F65354639-dd928f80-dba4-11e9-833b-bc3e8c6a737d.png&f=1&nofb=1&ipt=22bf038e2f077d2a4ed5eba3dc927930020dbf5f7a120552f94aacaab42a47c4" width="200px" />

A module, in Python, is a program that can be imported into interactive mode or other programs for use. A Python package typically comprises multiple modules. Physically, a package is a directory containing modules and possibly subdirectories, each potentially containing further modules. Conceptually, a package links all modules together using the package name for reference. 

NumPy (**Num**erical **Py**thon) is one of the most common packages used in Python. In fact, numerous computational packages that offer scientific capabilities utilize NumPy's array objects as a standard interface for data exchange. That's why, although NumPy doesn't inherently have scientific capabilities, understanding NumPy arrays and array-based computing principles can save your time in the future. 

NumPy offers a vast array of efficient methods for creating and manipulating numerical data arrays. Unlike Python lists, which can accommodate various data types within a single list, NumPy arrays require homogeneity among their elements for efficient mathematical operations. Utilizing NumPy arrays provides advantages such as faster execution and reduced memory consumption compared to Python lists. With NumPy, data storage is optimized through the specification of data types, enhancing code optimization.

In [150]:
import numpy as np

The array serves as a fundamental data structure within the NumPy. They represen a grid of values containing information on raw data, element location, and interpretation. Elements share a common data type, known as the array dtype.

One method of initializing NumPy arrays involves using Python lists, with nested lists employed for two- or higher-dimensional data structures.

In [151]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

We can access the elements through indexing. 

In [152]:
a[0]

np.int64(1)

Arrays are N-Dimensional (that's why sometimes we refer to them as NDarray). That means that NumPy arrays will encompass vector (1-Dimensions), Matrices (2D) or tensors (3D and higher). We can get all the information of the array by checking its attributes. 

In [153]:
a = np.array([[1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6]])
a

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [154]:
print('Dimensions/axes:', a.ndim)
print('Shape (size of array in each dimension):', a.shape)
print('Size (total number of elements):', a.size)
print('Data type:', a.dtype)


Dimensions/axes: 2
Shape (size of array in each dimension): (2, 6)
Size (total number of elements): 12
Data type: int64


We can initialize arrays using different commands depending on what we aim. 

For instance, the most straightforward case would be to pass a list to `np.array()` to create one: 

In [155]:
arr1 = np.array([5,6,7])
arr1

array([5, 6, 7])

However, sometimes we are more ambiguous and have no information on what our array contains. We just need to be able to initialize an array so that later on, our code, can update it. For this, we typically create arrays of the desired dimensions and fill them with zeros (`np.zeros()`), ones (`np.ones()`), with a given value (`np.full()`) or with without initializing (`np.empty()`). 

> Note: when working with large data, `np.empty()` can be faster and more efficient. Also, large arrays can take up most of your memory and, in those cases, carefully establishing the `dtype()` can help to manage memory more efficiently (i.e.,  chose 8 bits over 64 bits.)

In [156]:
np.zeros(4)

array([0., 0., 0., 0.])

In [157]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

Here you have an example of a 3D array of ones: if has 3 rows, 2 columns and 1 of height(depth)

In [158]:
np.ones((3,2,1))

array([[[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]]])

We can use `np.full()` to create an array of constant vales that we specify in the `fill_value` option. 

In [159]:
np.full((2,2,) , fill_value= 4)

array([[4, 4],
       [4, 4]])

When we use `np.empty()` we are creating an unitialized array, in the sense that it is reserving the requested space in memory and returns an array with 'garbage' values. 

In [160]:
np.empty(2)

array([0., 0.])

With `np.linspace()` we create an array with values that are equally spaced between the start and endpoint. For instance, in the below code we are creating an array with 5 equally spaced values from 0 to 20. 

In [161]:
np.linspace(start=0,stop=20,num=5)

array([ 0.,  5., 10., 15., 20.])

## **5.1 Managing array elements**

Arrays accept common operations like sorting, concatenating and finding unique elements. 

For instance, using the `sort()` method we can sort elements within an array. 

In [162]:
arr1 = np.array((10,2,5,3,50,0))
np.sort(arr1) # sort in ascending order by default

array([ 0,  2,  3,  5, 10, 50])

In [163]:
np.sort(arr1)[::-1] # sort in descending order by reversing the sorted array

array([50, 10,  5,  3,  2,  0])

In multidimensional arrays, we can sort the elements of a given dimension by specifying the axis (0 within columns, 1 across rows)

In [164]:
mat1 = np.array([[1,2,3],[8,1,5]])
mat1

array([[1, 2, 3],
       [8, 1, 5]])

In [165]:
mat1.sort(axis=0)
mat1

array([[1, 1, 3],
       [8, 2, 5]])

Using `concatenate` we can join the elements of two arrays along an existing axis. 

In [166]:
arr1 = np.array([1,2,3])
arr2 = np.array([6,7,8])

np.concatenate((arr1,arr2), axis=0)

array([1, 2, 3, 6, 7, 8])

Instead, if we want to concatenate along a new axis, we sue `vstack()` and `hstack()` 

In [167]:
np.vstack((arr1,arr2))

array([[1, 2, 3],
       [6, 7, 8]])

In [168]:
np.hstack((arr1,arr2)) # equivalent in this case to concatenate 

array([1, 2, 3, 6, 7, 8])

It is also possible to reshape arrays. For instance, let's reshape the concatenation of `arr1` and `arr2` to 3 rows and 2 columns

In [169]:
arr_c= np.concatenate((arr1,arr2))
arr_c.reshape((3,2))

array([[1, 2],
       [3, 6],
       [7, 8]])

We can also perform aggregation functions over all elements, like finding the minimum, maximum, means, sum of elements and much more. 

In [170]:
arr1

array([1, 2, 3])

In [171]:
print(arr1.min())
print(arr1.sum())
print(arr1.max())
print(arr1.mean())

1
6
3
2.0


It is also possible to get only the unique elements of an array or to count how many elements are repeated. 

In [172]:
arr1 =np.array((1,2,3,3,1,1,5,6,7,8,11,11))
np.unique(arr1)

array([ 1,  2,  3,  5,  6,  7,  8, 11])

In [173]:
unq, count = np.unique(arr1, return_counts=True)
count # First element appears 3 times, second 1... 

array([3, 1, 2, 1, 1, 1, 1, 2])

Comparing NumPy arrays is also possible using operators as `==`, `!=`, and the like. Comparisons will result in an array of booleans indicating if the condition is met for the cells. 

In [174]:
arr1 = np.array(((1,2,3),(4,5,6)))
arr2 = np.array(((1,5,3),(7,2,6)))
arr1==arr2

array([[ True, False,  True],
       [False, False,  True]])

## **5.2 Arithmetic operations with arrays**

From algebraic rules, we can only perform operations on an array and a scalar or with two arrays of the same shape. NumPy arrays support common operations as addition, substraction and multiplication as long as those two conditions are met. 

For NumPy, operations that happen within cells are what we know as **broadcasting**. **Broadcasting** is how NumPy operates between two arrays with different numbers of dimensions but compatible shape. 

In [175]:
A = np.array(((1,2,3),
                (4,5,6)))
B = np.array(((10,20,30),
                 (40,50,60)))

In [176]:
A.shape == B.shape

True

### **5.2.1. Element-wise operations** 

**Element-wise operations between arrays**

- Arrays must be of the same shape
- Element-wise addition, substraction, multiplication and division are performed with `+`, `-`, `*` and `/` respectively.

Mathematically, for $\mathbf A, \mathbf B \in \mathbb M^{n \times m}$ we are doing:

\begin{align*}
\mathbf A + \mathbf B 
\\
\mathbf A - \mathbf B
\\ 
\mathbf A \odot \mathbf B
\\
\mathbf A \oslash \mathbf B
\end{align*}

In [177]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [178]:
B

array([[10, 20, 30],
       [40, 50, 60]])

In [179]:
A+B # Matrix addition (element-wise addition)

array([[11, 22, 33],
       [44, 55, 66]])

In [180]:
A-B # Matrix subtraction (element-wise subtraction)

array([[ -9, -18, -27],
       [-36, -45, -54]])

In [181]:
A*B # Hadamard product (element-wise multiplication)

array([[ 10,  40,  90],
       [160, 250, 360]])

In [182]:
A/B # Hadamard division (element-wise division)

array([[0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1]])

**Element-wise operations between an array and a scalar**

- In this case, the scalar is broadcasted to match the shape of the array, allowing for element-wise operations.

- Mathematically, for a matrix $\mathbf A \in \mathbb M^{n \times m}$ and a scalar $c \in \mathbb R$ we are doing:

\begin{align*}
\mathbf A + c \mathbf 1_{n \times m} \\
\mathbf A - c \mathbf 1_{n \times m} \\
\mathbf A \odot c \mathbf 1_{n \times m} \\
\mathbf A \oslash c \mathbf 1_{n \times m}
\end{align*}

In [183]:
A+10

array([[11, 12, 13],
       [14, 15, 16]])

In [184]:
A-10

array([[-9, -8, -7],
       [-6, -5, -4]])

In [185]:
A*10

array([[10, 20, 30],
       [40, 50, 60]])

In [186]:
A/10

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6]])

### **5.2.2. Matrix multiplication** 

Matrix multiplication is achieved with either `@` or `matmul()`.

This is the usual matrix multiplication; for $\mathbf A, \mathbf B \in \mathbb M^{n \times m}$ we are doing:
$$
\mathbf A \mathbf B^\top
$$

> Note: because both of our matrices are 3-by-2, we need to transpose one of them to perform the multiplication.

In [187]:
print(f"{A.shape} * {B.T.shape} = {(A @ B.T).shape} matrix") # Matrix multiplication

(2, 3) * (3, 2) = (2, 2) matrix


In [188]:
A @ B.T

array([[140, 320],
       [320, 770]])

In [189]:
np.matmul(A,B.T)

array([[140, 320],
       [320, 770]])

In [190]:
print(f"{B.T.shape} * {A.shape} = {(B.T @ A).shape} matrix") # Matrix multiplication

print("\nUsing @\n", B.T @ A)
print("\nUsing matmul\n", np.matmul(B.T, A))

(3, 2) * (2, 3) = (3, 3) matrix

Using @
 [[170 220 270]
 [220 290 360]
 [270 360 450]]

Using matmul
 [[170 220 270]
 [220 290 360]
 [270 360 450]]


---

# **Practice exercies**

1.  Create a 1D array with all integer elemenets from 1 to 10 (both included). No hard-coding allowed!
2.  From the array you created in 1, create one that contains all odd elements and one with all even elements. 
3.  Create a new array that replaces all elements in 1 that are odd by -1. 
4.  Create a 3-by-3 matrix filled with 'True' values (i.e., booleans).
5.  Suppose you have array `a=np.array(['a','b','c','d','e','f','g'])` and `b = np.array(['g','h','c','a','e','w','g'])`. Find all elements that are equal. Can you get the position where the elements of both arrays match?
6.  Write a function that takes a element an array and prints elements that are divisible by a given number. Try it creating an array from 1 to 20 and printiing divisibles by 3.  
7. Consider two matrices, A and B, both of size 100x100, filled with random integer values between 1 and 10. Implement a function to perform element-wise multiplication of these matrices using nested loops. Implement the same operation using Numpy's vectorized multiplication. Repeart againnwith matrices of size 1000x1000, 10000x10000, 1000000x1000000 and compare the execution time. Which one is faster? 


In [191]:
#1. 
array_ex = np.array(range(1,11))
print(array_ex)

[ 1  2  3  4  5  6  7  8  9 10]


In [192]:
#2. 
odds = [o for o in array_ex if o%2==1]
print(odds)
even = [o for o in array_ex if o%2==0]
print(even)

[np.int64(1), np.int64(3), np.int64(5), np.int64(7), np.int64(9)]
[np.int64(2), np.int64(4), np.int64(6), np.int64(8), np.int64(10)]


In [193]:
#3. 
arr_r = array_ex
arr_r = np.where(arr_r%2,arr_r,-1)
arr_r

array([ 1, -1,  3, -1,  5, -1,  7, -1,  9, -1])

In [194]:
#4. 
mat3 = np.full((3,3),fill_value =True,dtype=bool)
mat3
print('Congrats, you just created your first mask!')

Congrats, you just created your first mask!


In [195]:
#5. 
a=np.array(['a','b','c','d','e','f','g'])
b = np.array(['g','h','c','a','e','w','g'])
inter=np.intersect1d(a,b)
print(inter)

inter, apos, bpos = np.intersect1d(a,b,return_indices=True)
print(apos)
print(bpos)

['a' 'c' 'e' 'g']
[0 2 4 6]
[3 2 4 0]


In [196]:
#6. 
def print_divisible(array,div):
    for i in array: 
        if i%div == 0:
            print(i,'is divisible by', div)
    return None

arr =np.array(range(1,21))
print_divisible(arr,3)

3 is divisible by 3
6 is divisible by 3
9 is divisible by 3
12 is divisible by 3
15 is divisible by 3
18 is divisible by 3


In [197]:
#7
mat_a =np.random.randint(1, 11, size=(1000, 1000))
mat_b =np.random.randint(1, 11, size=(1000, 1000))

def multiply_in_loop(m1,m2):
    if m1.shape != m2.shape:
        raise ValueError("Matrices A and B must have the same shape.")

    m, n = m1.shape
    result = np.zeros((m, n))

    for i in range(m):
        for j in range(n):
            result[i, j] = m1[i, j] * m2[i, j]

    return result


In [198]:
out= multiply_in_loop(mat_a,mat_b)


In [199]:
out_built = np.multiply(mat_a,mat_b)

In [200]:
(out_built == out).sum()

np.int64(1000000)