## 2025/10/02 TA Session 1
Notes: to catch up: NumPy and Pandas
### Reivew of Python code
1. comment syntax

In [2]:
# to comment chunk of Code
# see how it works on macos
# the shortcut should be Cmd + /
# to uncomment, use the same shortcut

# alternatively, you can use triple quotes
"""
This is a block comment
that spans multiple lines
""" 

'\nThis is a block comment\nthat spans multiple lines\n'

2. using f to insert in print command

In [4]:
# use f to insert in print command
name = "Alice"
age = 30
print(f"{name} is {age} years old.")

# the syntax f"..." is used to create formatted string literals,
# just add f before the opening quotation mark of the string.
# and use curly braces {} to embed expressions inside the string.
# inside {}, it should be valid python expressions.
# for example, you can do calculations inside {}
a = 5
b = 10
print(f"The sum of {a} and {b} is {a + b}.")    
# output: The sum of 5 and 10 is 15.

Alice is 30 years old.
The sum of 5 and 10 is 15.


3. object and method

In [5]:
# there are pre-defined objects in python, such as string, list, dictionary, etc.
# each object has its own methods (functions associated with the object)
# for example, string object has methods like .upper(), .lower(), .replace(), etc
# besides method, attributes are also associated with objects
# for example, string object has attribute .length
# attribute is like property of the object, method is like action of the object
# to access method or attribute, use dot notation: object.method() or object.attribute

4. variables

In [ ]:
# no need to declare variable type in python,
# but to declare, we can use type hints
x: int = 10          # x is an integer
y: float = 3.14     # y is a float
name: str = "Bob"   # name is a string
is_student: bool = True  # is_student is a boolean
# however, python is dynamically typed, so the type can change
x = "Now I'm a string"  # x is now a string

5. container data type

In [ ]:
# tuple, list, set, dictionary
# tuple is immutable, use parentheses ()
my_tuple = (1, 2, 3)
# list is mutable, use square brackets []
my_list = [1, 2, 3]
# set is unordered collection of unique elements, use curly braces {}
my_set = {1, 2, 3}
# dictionary is key-value pairs, use curly braces {}
my_dict = {"name": "Alice", "age": 30}
# access dictionary value by key
my_dict["name"]  # returns "Alice"
my_dict["age"]   # returns 30
# add new key-value pair
my_dict["is_student"] = False
# update value
my_dict["age"] = 31
# remove key-value pair
del my_dict["is_student"]   
# we can append to list, but not to tuple
my_list.append(4)  # my_list is now [1, 2, 3, 4]
# my_tuple.append(4)  # this will raise an Attribute
# each container type can contain different data types
mixed_list = [1, "two", 3.0, True, [5, 6], (7, 8), {9, 10}, {"key": "value"}]

5. function, branching, looping

### Intro to NumPy

In [7]:
# NumPy is a library I need to import
import numpy as np
# a library is a collection of pre-written code that we can use to perform specific tasks
# how to use np
array1 = np.array([1, 2, 3, 4, 5])
print(array1)
# output: [1 2 3 4 5]
# create a 2D array (matrix)
matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix1)
# output:
# [[1 2 3]
#  [4 5 6]]
# array is not in python built-in data type, it is provided by NumPy library
# .array() is a method of NumPy library to create an array
# indexing in NumPy array
print(array1[0])  # output: 1
print(matrix1[0, 1])  # output: 2

array1 = np.array([1, 2, 3, 4])
print(array1.mean())     # 数组方法
print(np.mean(array1))   # NumPy 函数
# the difference between array method and NumPy function
# array method is called on the array object, it operates on that specific array
# NumPy function is called on the NumPy library, it can operate on any array passed

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
1
2
2.5
2.5


# **Practice exercies** 
3.  Create a new array that replaces all elements in 1 that are odd by -1. 
4.  Create a 3-by-3 matrix filled with 'True' values (i.e., booleans).
5.  Suppose you have array `a=np.array(['a','b','c','d','e','f','g'])` and `b = np.array(['g','h','c','a','e','w','g'])`. Find all elements that are equal. Can you get the position where the elements of both arrays match?
6.  Write a function that takes a element an array and prints elements that are divisible by a given number. Try it creating an array from 1 to 20 and printiing divisibles by 3.  
7. Consider two matrices, A and B, both of size 100x100, filled with random integer values between 1 and 10. Implement a function to perform element-wise multiplication of these matrices using nested loops. Implement the same operation using Numpy's vectorized multiplication. Repeart againnwith matrices of size 1000x1000, 10000x10000, 1000000x1000000 and compare the execution time. Which one is faster? 


In [ ]:
# 1: Create a 1D array with all integer elemenets from 1 to 10 (both included). No hard-coding allowed!
array_1_to_10 = np.arange(1, 11)
print(array_1_to_10)
# output: [ 1  2  3  4  5  6  7  8  9 10]

# 2.  From the array you created in 1, create one that contains all odd elements and one with all even elements.


### Intro to pandas

In [ ]:
# series, dataframe
# series for single variable, dataframe for multiple variables

# slicing
